### ISSUE TITLE
Unable to find the secondary indicator settings in ACP

### ISSUE THREAD

**Issue by abhaysv** [aXenDeveloper/ips-secondary-groups-indicator#1]
Unfortunately, the plugins install's successfully but im unable to locate the secondary indicator settings in ACP

**Comment by aXenDeveloper** [comment]
Settings is in a Plugins section.
![image](https://user-images.githubusercontent.com/58148176/108496298-27a40700-72aa-11eb-8b9c-f7792e91aa07.png)

**Comment by abhaysv** [comment]
Thanks
