### ISSUE TITLE
Spacing Idea/Question

### ISSUE THREAD

**Issue by CapBlackShot** [aXenDeveloper/ips-secondary-groups-indicator#4]
Hi @aXenDeveloper,

You've been releasing great updates - thanks for that!

Quick question: would you be able to add an option to set the spacing between group icons? My settings are set to show icons only, but the space between them is a bit too large.

Or could you tell me where to find that in your codes?

Thanks!

**Comment by aXenDeveloper** [comment]
You can add style in your theme yourself.

**Comment by CapBlackShot** [comment]
> You can add style in your theme yourself.

Sure thing, but could you tell me how to change the spacing between group icons then, if I choose to display icons only? I thought I would have to do that in your XML.

**Comment by aXenDeveloper** [comment]
```
.cAuthorPane_info > li[data-role="axen-group-icon"],
.cAuthorPane_info > li[data-role="axen-group-icon-secondary"] {
  border-bottom: 1px solid #000;
}
```

**Comment by CapBlackShot** [comment]
> ```
> .cAuthorPane_info > li[data-role="axen-group-icon"],
> .cAuthorPane_info > li[data-role="axen-group-icon-secondary"] {
>   border-bottom: 1px solid #000;
> }
> ```

Thanks @aXenDeveloper. I've added that to custom.css but it actually added a spacing line. What I meant to change was the gap/distance between group icons - how distant or close they are from one another. I tried replacing _border-bottom_ with _margin_ but still no luck.
