### ISSUE TITLE
Bugs on profile page

### ISSUE THREAD

**Issue by hks27d** [aXenDeveloper/ips-secondary-groups-indicator#5]
### Introduction
Hello! The plugin has an issue on the profile page of the users. I'll explain below. Please take into consideration that the issues are related to the profile page of the users only. I marked the advertisements using white color (so don't take this into consideration) and I marked the exact issue using red color.

Please see the photo below.

![11111](https://user-images.githubusercontent.com/51793958/160508886-bc9c4b89-85fa-4c6e-890b-ae7a5db31859.PNG)

### What is te real issue
The plugins does its job and it's showing the code inside _#elProfileInfoColumn > div.ipsBox_, inside topics and inside hover card. However, the real issue is the following one: the plugin leaves a big white space in the footer or above the footer in some situations (on users profile pages).
It ruins the whole HTML page.

### Some details
I should mention the fact that we are running the latest version of IPS (Invision Community v4.6.11) at the minute. The template is fully compatible with the platform. It was recently updated and all bugs were fixed by the developer. We don't have many extensions or plugins on our community either.

### Steps that I took into consideration when testing
- Changing selector is not working: I've just tried to see if the problem is related to this, but even if we change the CSS class or id for which the plugin is looking for, this will not be fixed.
- Changing type is not working: I've just tried some things there, one by one: add_after, add_inside_start, add_inside_end.
- Changing content; I completely removed the whole thing and added a simple 'x' character in order to see if the problem is caused by some mistakes. It's not working.

### Steps in order to replicate the issue:
1. Make sure that the user has 0 posts, 0 topics, 0 activity (it's a new registered user with 0 content or activity)
2. Set primary group to anything
3. Set secondary group to one or more groups

### I have to mention the following things
- I tested this with CloudFlare OFF + cleaning cache of the platform itself + cleaning cache and cookies from my browser
- I tested with CloudFlare ON, but keeping Development mode ON at the same time + cleaning cache of the platform itself + cleaning cache and cookies from my browser
- Other people report the same issues
- It's not related to the template or the version of Invision Community or other plugins/extensions installed. I say that because we do not have other plugins/extensions which interact with User Profile page
- We've just tested on the default template from IPS, but there it doesn't show up at all and the page remains intact (as nothing was added inside _#elProfileInfoColumn_)
- There's nothing related to Custom CSS, as I've just checked every CSS class inside custom.css to see if we are rewriting some things there

### Final words
Thank you for you work! We really appreciate it. @aXenDeveloper 
We are looking forward for a reply from you.

**Comment by aXenDeveloper** [comment]
Hi,
I cannot reproduce this error.
![localhost_ipsdev_index php__profile_4-test1_](https://user-images.githubusercontent.com/58148176/160675809-25945341-9deb-4c51-9807-6eaf8a33e11e.png)

Please provide step by step how I can reproduce this error.

**Comment by hks27d** [comment]
Hello!
Thank you for checking. The exact steps provided are in the first reply. There is nothing else to add.

I was able to solve this issue by searching for _replog_ in the template. I did some code alterations. However, that's not a permanent fix.
In core - front - profile > profile there are some lines to check {{if member.group['gbw_view_reps']}}, to see if the URL will be put in place by the platform or not. 

I'm not really sure if your IPS plugin is buggy or the template.
Seeing that it's working on other templates makes me think that the issue may be generated because of the template itself, rather than the code of your plugin.

Are you able to test it on IPS Focus templates? Do you have the last version of IPS + the last version of a template from IPS Focus? We only have one template at the minute and can't do more tests.
Or can you test it on other templates if you don't have IPS Focus? Thank you!

**Comment by aXenDeveloper** [comment]
I don't have the IPS Focus theme.

**Comment by hks27d** [comment]
@aXenDeveloper Hello!
I was looking for a solution from the main IPSFocus developer (thanks for that).
We've setted 4 templates (1 the current one used by the community, 1 default ips template, 1 default ipsfocus template, 1 ipsfocus template with all of our modifications). Nothing's really solved on either one.

Check this photo: https://i.postimg.cc/1XrG3Z55/conclusion.png
IPS Default Template seems to have some bugs too. I found the same results as him when I checked, a few days ago.
I don't to find anything wrong with your plugin code either. But something it's just not working as expected.

Can you have a look at it?
Are you available to check with us? We can provide all the needed accesses and permissions on our IPS installation.
Is there any other way to talk in a faster way instead of writing Git comments?

We're looking forward for a reply from you.
Thank you!

**Comment by hks27d** [comment]
I was looking for a solution from the main IPSFocus developer (thanks for that).
We've setted 4 templates (1 the current one used by the community, 1 default ips template, 1 default ipsfocus template, 1 ipsfocus template with all of our modifications). Nothing's really solved on either one.

Check this photo: https://i.postimg.cc/1XrG3Z55/conclusion.png
IPS Default Template seems to have some bugs too. I found the same results as him when I checked, a few days ago.
I don't to find anything wrong with your plugin code either. But something it's just not working as expected.

Can you have a look at it?
Are you available to check with us? We can provide all the needed accesses and permissions on our IPS installation.
Is there any other way to talk in a faster way instead of writing Git comments?

We're looking forward for a reply from you.
Thank you!

**Comment by aXenDeveloper** [comment]
You can write to me in a private message on the IPS forum.
https://invisioncommunity.com/profile/580858-axendev/
